### PR TITLE
new radial basis sets

### PR DESCRIPTION
**Pull request by JPDarby**
I've added in the option to  use some alternative radial basis sets for the density expansion in SOAP
Syntax is `radial_basis=GTO` and the options are 

1. "ORIGINAL": original equispaced gaussians. default option
2. "POLY": polynomials defined in original SOAP [paper ](https://doi.org/10.1103/PhysRevB.87.184115)
3. "GTO": (primitive) Gaussian-type orbitals with alpha_nl set similarly to as suggested in [dscribe paper](https://doi.org/10.1016/j.cpc.2019.106949)

Extending this to other choices of radial basis involves

1.  specifying the overlap between basis functions (including r^2 factor) 
2.  evaluating the basis functions on a radial grid. The current default is to evaluate on a `3*n_max` grid

### CODE REVIEW

**Comment by gabor1** [comment]
Can we have ORIGINAL -> EQUI_SPC_GAUSS

**Comment by gabor1** [comment]
And why not make the better basis the default?

**Comment by bernstei** [comment]
To not break old command lines?

**Comment by albapa** [comment]
I think there are two issues here:
- how old potentials work
- reproduce old command lines

The first one can be solved using the `GAP_VERSION` and the `xml_label` mechanism, which should automatically default to the appropriate behaviour.

The second one is more tricky, but one can argue that getting a better potential is beneficial. It could still be problematic if the same parameters would result in an inferior potential, e.g. because `n_max` is specified and now should be better

**Comment by albapa** [comment]
> Can we have ORIGINAL -> EQUI_SPC_GAUSS

Can we just do `EQUISPACED_GAUSS`. Not much longer but reads better.

**Comment by albapa** [comment]
Yes, this is a good plan. @JPDarby please replace `ORIGINAL` with `EQUISPACED_GAUSS ` add the code for the `xml_version` check - for now use a suitably large number to compare with, which we can replace when we decide to switch. We can merge once these are done.

**Comment by JPDarby** [comment]
Yes, sounds good to me

**Pull request merged**
