### PR TITLE
fix general_trimer 

### PR DESCRIPTION
**Pull request by sujona**
resolves libAtoms/QUIP#632

### CODE REVIEW

**Comment by gabor1** [comment]
hi Jonatan, this looks good, thanks for your work on this. One small request: instead of hardcoding the string length to be 9, can you give a more descriptive name for this new length, and define in where the other sting lengths are defined, so that later it can be adjusted more easily should that be required?

**Comment by sujona** [comment]
OK, yes I fixed it locally. But the string lengths are defined in QUIP/src/libAtoms/Dictionary.f95. I'm not really used to the git submodules. Do I make a pull request on each reapo separately? It will break GAP if QUIP is not up to date, not the other way around though. 

Also when I looked for the instances, I saw that `molecule_lo_d_initialise` has the same problem in the line 
```
character(len=STRING_LENGTH), dimension(99) :: signature_fields, row_fields, append_rows, template_rows
```
which will also segfault with the default STRING_LENGTH with openMP. In the `signature_field` arrays each entry contain an atomic number in string format which means that len=3 will always be enough. But I don't know what could enter these other fields.

**Comment by gabor1** [comment]
I can define you a new constant in libAtoms, and then you can just use it here. How about CHEMICAL_FORMULA_STRING_LENGTH, and setting it to 20?

**Comment by sujona** [comment]
Unless I'm wrong it's the atomic number, so I used STR_LEN_ATOMIC_NUM, but anything will do. Or possibly a more generic thing like STR_LEN_SHORT=200, that can be used for for instances where anything beyond a few characters or words is unexpected.

**Comment by gabor1** [comment]
I added a STRING_LENGTH_SHORT to Dictionary.f95, so you can use it now (defaults to 32).

**Comment by sujona** [comment]
Ok, great. And for the character arrays in `molecule_lo_d_initialise`, for the two of them ending with `_filed` I used the SHORT length since they contain single integer strings. Then there's only two left with `STRING_LENGTH` and `dimension(99)` which which is under the segfault limit.

**Pull request merged**
